// Generated by @vite-pwa/nuxt
import type { AppleSplashScreenLink, FaviconLink, HtmlLink, IconAsset } from '@vite-pwa/assets-generator/api'

export interface PWAAssetIconImage {
  width?: number
  height?: number
  key: string
  src: string
}
export type PWAAssetIcon<T extends HtmlLink> = Omit<IconAsset<T>, 'buffer'> & {
  asImage: PWAAssetIconImage
}
export interface PWAIcons {
  transparent: Record<'pwa-64x64.png' | 'pwa-192x192.png' | 'pwa-512x512.png', PWAAssetIcon<HtmlLink>>
  maskable: Record<'maskable-icon-512x512.png', PWAAssetIcon<HtmlLink>>
  favicon: Record<'favicon.ico' | 'favicon.svg', PWAAssetIcon<FaviconLink>>
  apple: Record<'apple-touch-icon-180x180.png', PWAAssetIcon<HtmlLink>>
  appleSplashScreen: Record<string, PWAAssetIcon<AppleSplashScreenLink>>
}

declare module '#app' {
  interface NuxtApp {
    $pwaIcons?: PWAIcons
  }
}

declare module 'vue' {
  interface ComponentCustomProperties {
    $pwaIcons?: PWAIcons
  }
}

export {}
